name: Build memkv

on:
  workflow_dispatch:

permissions:
  contents: read # for actions/checkout to fetch code

env:
 BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 

# Add to run name based on branch name
run-name: Build memkv from ${{ env.BRANCH_NAME }}

# Limiting concurrency
concurrency: ci-${{ env.BRANCH_NAME }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.18' ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      
      # You can test your matrix by printing the current Go version
      - name: Display Go version
        run: go version

